import { Header, Icon, Logo, WorldMap } from "./components";

const services = [
  { icon: "code", title: "Software Development", text: "Enterprise-grade custom software engineered for scale, security, and longevity. From architecture to deployment, we build systems that power critical operations worldwide." },
  { icon: "phone", title: "Mobile Applications", text: "Native and cross-platform mobile experiences that reach users wherever they are. Precision-crafted for performance, accessibility, and global markets." },
  { icon: "globe", title: "Digital Platforms", text: "Scalable digital ecosystems connecting businesses, services, and users. We design and operate platforms that become the infrastructure of industries." },
  { icon: "cloud", title: "Online Services", text: "End-to-end digital service delivery — from SaaS products to managed online operations. Reliable, secure, and built for continuous availability." },
  { icon: "chip", title: "Technology Solutions", text: "Bespoke technology consulting and implementation for complex organisational challenges. We translate strategic vision into operational reality." },
];
const strengths = [
  { icon: "shield", title: "Enterprise-Grade Security", text: "ISO-aligned security standards and end-to-end encryption across all systems and data flows." },
  { icon: "check", title: "GDPR Compliant", text: "Full compliance with GDPR and international data protection regulations across all jurisdictions." },
  { icon: "bolt", title: "99.9% Uptime SLA", text: "Guaranteed service availability backed by redundant infrastructure and 24/7 monitoring." },
  { icon: "server", title: "Global Delivery", text: "Distributed teams and delivery centres ensuring consistent quality across every timezone." },
];

export default function Home() {
  return <><Header /><main id="home">
    <section className="hero"><div className="hero-grid" /><div className="container hero-content"><div className="eyebrow hero-badge"><span /> Global Technology Leader</div><h1>Engineering the Future of<br className="desktop-break" /> Global Technology</h1><p className="hero-description">Floreza Technologies delivers world-class software, platforms, and digital<br className="desktop-break" /> solutions trusted by organisations, financial institutions, and partners<br className="desktop-break" /> across 40+ countries.</p><div className="button-group"><a className="button button-gold" href="#solutions">Explore Our Solutions <Icon name="arrow" /></a><a className="button button-subtle" href="#businesses">Our Businesses <Icon name="arrow" /></a></div><div className="hero-map"><WorldMap /></div></div></section>
    <section className="stats" aria-label="Floreza in numbers"><div className="container stats-grid">{[["15+", "Years of Excellence"], ["40+", "Countries Served"], ["500+", "Projects Delivered"], ["200+", "Professionals Worldwide"]].map(([value,label]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
    <section className="services section" id="businesses"><div className="container"><div className="section-heading"><span className="eyebrow">What We Do</span><h2>Five Pillars of Global Technology</h2><p>From enterprise software to digital platforms, our five core divisions<br className="desktop-break" /> deliver end-to-end technology solutions at global scale.</p></div><div className="services-grid" id="solutions">{services.map(service => <article className="service-card" key={service.title}><span className="icon-box"><Icon name={service.icon} /></span><h3>{service.title}</h3><p>{service.text}</p><a href={`mailto:info@florezatechnologies.com?subject=${encodeURIComponent(service.title + " enquiry")}`}>Learn more <Icon name="arrow" /></a></article>)}<div className="service-decoration" aria-hidden="true"><span className="decoration-mark">F</span><span>Technology. Without boundaries.</span></div></div></div></section>
    <section className="reach section" id="about"><div className="container reach-grid"><div><span className="eyebrow">Global Reach</span><h2>Operating Across 40+<br /> Countries</h2><p>From emerging markets to established financial centres, Floreza Technologies operates with the rigour and reliability that global institutions demand. Our distributed teams deliver consistent excellence across every timezone.</p><ul className="reach-list"><li>Offices and partners across Asia, Europe, and the Americas</li><li>Multilingual delivery teams serving local and global clients</li><li>24/7 operations supporting mission-critical systems worldwide</li><li>Compliant with international data protection and security standards</li></ul><a className="button" href="#why-floreza">Learn About Us <Icon name="arrow" /></a></div><div className="reach-map"><WorldMap compact /></div></div></section>
    <section className="why section" id="why-floreza"><div className="container"><div className="section-heading"><span className="eyebrow">Why Floreza</span><h2>Built for the demands of global enterprise</h2></div><div className="strengths-grid">{strengths.map(item => <article className="strength-card" key={item.title}><span className="icon-box"><Icon name={item.icon} /></span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
    <section className="contact section" id="contact"><div className="container"><div className="contact-panel"><span className="eyebrow">Start a Conversation</span><h2>Ready to build something exceptional?</h2><p>Whether you need a technology partner for a complex<br className="desktop-break" /> transformation or a team to deliver a specific solution, we are<br className="desktop-break" /> ready to engage.</p><div className="button-group"><a className="button button-gold" href="mailto:info@florezatechnologies.com"><Icon name="mail" /> Contact Our Team</a><a className="button button-subtle" href="#solutions">View Our Solutions <Icon name="arrow" /></a></div></div></div></section>
    <section className="additional-info container" aria-label="Company information"><details id="careers"><summary>Careers at Floreza <Icon name="arrow" /></summary><p>Interested in building technology for a global audience? Introduce yourself at <a href="mailto:info@florezatechnologies.com?subject=Career%20enquiry">info@florezatechnologies.com</a>.</p></details><details id="news"><summary>Company news <Icon name="arrow" /></summary><p>Company updates will be shared here. For press and partnership enquiries, <a href="mailto:info@florezatechnologies.com?subject=Press%20enquiry">contact our team</a>.</p></details></section>
  </main><footer className="footer"><div className="container"><div className="footer-grid"><div className="footer-brand"><Logo /><p>Engineering the future of global technology.<br />Trusted by organisations, financial<br /> institutions, and partners across 40+<br /> countries.</p><a href="mailto:info@florezatechnologies.com"><Icon name="mail" /> info@florezatechnologies.com</a><a href="#home"><Icon name="globe" /> florezatechnologies.com</a></div><div><h4>Company</h4><a href="#about">About Us</a><a href="#careers">Careers</a><a href="#news">News</a></div><div><h4>Solutions</h4>{services.map(service => <a href="#solutions" key={service.title}>{service.title}</a>)}</div><div><h4>Legal</h4><a href="mailto:info@florezatechnologies.com?subject=Privacy%20policy%20request">Privacy Policy</a><a href="mailto:info@florezatechnologies.com?subject=Terms%20and%20conditions%20request">Terms &amp; Conditions</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Floreza Technologies. All rights reserved.</span><a href="#home">florezatechnologies.com <span>↗</span></a></div></div></footer></>;
}
