import type { Metadata } from "next";
import { Icon } from "../components";
import { capabilities, industries, platforms } from "../site-content";
import { BulletList, CallToAction, PageHero, SectionHeading, Steps } from "../site-ui";

export const metadata: Metadata = { title: "Technology & Solutions | Floreza Technologies" };

export default function Technology() {
  return <main id="main-content" className="inner-page technology-page"><PageHero label="Technology & Solutions" title="The Technical Foundation Behind Global Delivery" description="Floreza Technologies combines deep engineering expertise, proprietary platforms, and emerging technology capabilities to deliver solutions that perform at enterprise scale." />
    <section className="section surface"><div className="container"><SectionHeading label="Core Capabilities" title="Engineering excellence across every discipline" description="Our technical capabilities span the full spectrum of modern enterprise technology — from foundational architecture to cutting-edge AI integration." /><div className="three-card-grid">{capabilities.map(item => <article className="content-card dark-card capability-card" key={item.title}><span className="icon-box"><Icon name={item.icon} /></span><h3>{item.title}</h3><p>{item.text}</p><div className="tags">{item.tags.map(tag => <span key={tag}>{tag}</span>)}</div></article>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading label="Platforms" title="Proprietary platforms built for enterprise demands" description="Beyond bespoke development, Floreza Technologies operates a suite of proprietary platforms that accelerate delivery and reduce risk for our clients." /><div className="two-card-grid">{platforms.map(item => <article className="content-card platform-card" key={item.title}><span className="eyebrow">{item.label}</span><h3>{item.title}</h3><p>{item.text}</p><BulletList items={item.features} /></article>)}</div></div></section>
    <section className="section surface"><div className="container"><SectionHeading label="Solutions by Industry" title="Tailored solutions for complex sectors" description="Our technology capabilities are applied across industries where precision, security, and reliability are non-negotiable." /><div className="two-card-grid">{industries.map(item => <article className="content-card dark-card industry-card" key={item.title}><h3>{item.title}</h3><p>{item.text}</p><BulletList items={item.features} /></article>)}</div></div></section>
    <section className="section"><div className="container split-grid"><div><span className="eyebrow">Our Approach</span><h2>How we deliver</h2><p>Every engagement follows a structured delivery methodology that balances rigour with agility — ensuring predictable outcomes without sacrificing the flexibility that complex projects demand.</p></div><Steps items={[
      { title: "Discovery & Architecture", text: "We invest in deep discovery before writing a line of code — understanding your systems, constraints, and objectives to design an architecture that will serve you for years, not months." },
      { title: "Iterative Delivery", text: "Structured sprints with clear milestones, continuous integration, and regular client reviews. You see working software early and often — not at the end of a long waterfall." },
      { title: "Security by Design", text: "Security reviews, threat modelling, and penetration testing are embedded throughout delivery — not bolted on at the end. Every system we build is designed to withstand scrutiny." },
      { title: "Transition & Support", text: "Comprehensive knowledge transfer, documentation, and post-launch support ensure your team can operate and evolve what we build together. We do not disappear at go-live." },
    ]} /></div></section><CallToAction label="Start a Technical Conversation" title="Discuss your technology challenge with our team" text="Whether you are modernising legacy infrastructure, building a new platform, or integrating AI into your operations, our technical team is ready to engage." secondaryLabel="Our Businesses" secondaryHref="/businesses" />
  </main>;
}
